export { default as AirSweeper01 } from '@/public/assets/defenses/air_sweeper/air_sweeper_01.webp'
export { default as AirSweeper02 } from '@/public/assets/defenses/air_sweeper/air_sweeper_02.webp'
export { default as AirSweeper03 } from '@/public/assets/defenses/air_sweeper/air_sweeper_03.webp'
export { default as AirSweeper04 } from '@/public/assets/defenses/air_sweeper/air_sweeper_04.webp'
export { default as AirSweeper05 } from '@/public/assets/defenses/air_sweeper/air_sweeper_05.webp'
export { default as AirSweeper06 } from '@/public/assets/defenses/air_sweeper/air_sweeper_06.webp'
export { default as AirSweeper07 } from '@/public/assets/defenses/air_sweeper/air_sweeper_07.webp'
