export { default as GigaTesla01 } from '@/public/assets/defenses/giga_tesla/giga_tesla_01.webp'
export { default as GigaTesla02 } from '@/public/assets/defenses/giga_tesla/giga_tesla_02.webp'
export { default as GigaTesla03 } from '@/public/assets/defenses/giga_tesla/giga_tesla_03.webp'
export { default as GigaTesla04 } from '@/public/assets/defenses/giga_tesla/giga_tesla_04.webp'
export { default as GigaTesla05 } from '@/public/assets/defenses/giga_tesla/giga_tesla_05.webp'
